version: '3.7'

#environment JAVA_HOME=/usr/bin/java

services:
  redis1:
    image: redis:latest
    container_name: redis_cache
    hostname: redis1
    restart: on-failure
    ports:
      - "6379:6379"
  better-banking:
    image: stuholland/better-banking:1.0.0
    container_name: better_banking
      hostname: banking
      restart: on-failure
      ports:
        - "9000:9000"
      environment:
        io_betterbanking_url-base: http://localhost:8080